export const earlyStageInvestors = [
  "Alliance Venture",
  "Arkwright X",
  "Antler",
  "Born",
  "Construct Venture",
  "Endeavor Investor",
  "Føyen Torkildsen",
  "Gate Ventures",
  "Hadean Ventures",
  "Idékapital",
  "Investinor",
  "Kistefos",
  "SORS",
  "Norselab",
  "Northzone",
  "Nysnø",
  "Pre Seed Ventures",
  "Proventure",
  "Reodor Ventures",
  "Sarsia Seed",
  "SNÖ Ventures",
  "StartupLab",
  "Summa Equity",
  "Viking Venture",
  "Wider Impact",
  "Kaptein",
];

export const seriesAInvestors = [
  "Altor Equity Partners",
  "Alliance Venture",
  "Arkwright X",
  "Creandum",
  "EQT Ventures",
  "Frumtak Ventures",
  "HitecVision",
  "Idekapital",
  "Investinor",
  "Kistefos",
  "Northzone",
  "Nysnø",
  "Reodor Ventures",
  "Sarsia Seed",
  "Schibsted Growth",
  "SNÖ Ventures",
  "SORS",
  "Summa Equity",
  "Sundt",
  "Verdane Capital",
  "Viking Venture",
  "Vito Ventures",
  "Wider Impact",
  "Wings Invest",
];

export const founders = [
  "Ane Bjørnsen",
  "Andreas Thorsheim",
  "Bjørn Tore Jensen",
  "Christina Heide",
  "Erik Fjellborg",
  "Even Heggernes",
  "Frida Polli",
  "Håkon Tandberg",
  "Ingrid Teigland Akay",
  "Jens Petter Hauge",
  "Karoline Lunde",
  "Kristoffer Tonning",
  "Lars Boilesen",
  "Magnus Grimeland",
  "Marius Johansen",
  "Nina Jensen",
  "Ole Eidhammer",
  "Ragnhild Steen",
  "Silje Vallestad",
];
